package pentu.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static pentu.Elain.*;
import pentu.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.18 03:05:48 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ElainTest {



  // Generated by ComTest BEGIN
  /** testKaannaPv86 */
  @Test
  public void testKaannaPv86() {    // Elain: 86
    String pv = "22.02.1997"; 
    String uusi = kaannaPv(pv); 
    assertEquals("From: Elain line: 89", "1997.02.22", uusi); 
    String pv1 = "22.02."; 
    assertEquals("From: Elain line: 91", "0000.02.22", kaannaPv(pv1)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi293 */
  @Test
  public void testRekisteroi293() {    // Elain: 293
    Elain mirz1 = new Elain(); 
    assertEquals("From: Elain line: 295", 0, mirz1.getTunnusNro()); 
    mirz1.rekisteroi(); 
    Elain mirz2 = new Elain(); 
    mirz2.rekisteroi(); 
    int n1 = mirz1.getTunnusNro(); 
    int n2 = mirz2.getTunnusNro(); 
    assertEquals("From: Elain line: 301", n2 - 1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse330 */
  @Test
  public void testParse330() {    // Elain: 330
    Elain elain = new Elain(); 
    elain.parse("   2  |  Karvatassu Mirzam   | Nelli"); 
    assertEquals("From: Elain line: 333", 2, elain.getTunnusNro()); 
    assertEquals("From: Elain line: 334", true, elain.toString().startsWith("2|Karvatassu Mirzam|Nelli|"));  // on enemmäkin kuin 3 kenttää, siksi loppu |
    elain.rekisteroi(); 
    int n = elain.getTunnusNro(); 
    elain.parse(""+(n+20));  // Otetaan merkkijonosta vain tunnusnumero
    elain.rekisteroi();  // ja tarkistetaan että seuraavalla kertaa tulee yhtä isompi
    assertEquals("From: Elain line: 340", n+20+1, elain.getTunnusNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString431 */
  @Test
  public void testToString431() {    // Elain: 431
    Elain elain = new Elain(); 
    elain.parse("   2  |  Karvatassu Mirzam   | Nelli"); 
    assertEquals("From: Elain line: 434", true, elain.toString().startsWith("2|Karvatassu Mirzam|Nelli|"));  // on enemmäkin kuin 3 kenttää, siksi loppu |
  } // Generated by ComTest END
}