package pentu.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static pentu.Elain.*;
import pentu.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.23 23:44:15 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ElainTest {



  // Generated by ComTest BEGIN
  /** testKaannaPv97 */
  @Test
  public void testKaannaPv97() {    // Elain: 97
    String pv = "22.02.1997"; 
    assertEquals("From: Elain line: 99", "1997.02.22", kaannaPv(pv)); 
    String pv1 = "22.02."; 
    assertEquals("From: Elain line: 101", "0000.02.22", kaannaPv(pv1)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi244 */
  @Test
  public void testRekisteroi244() {    // Elain: 244
    Elain mirz1 = new Elain(); 
    assertEquals("From: Elain line: 246", 0, mirz1.getTunnusNro()); 
    mirz1.rekisteroi(); 
    Elain mirz2 = new Elain(); 
    mirz2.rekisteroi(); 
    int n1 = mirz1.getTunnusNro(); 
    int n2 = mirz2.getTunnusNro(); 
    assertEquals("From: Elain line: 252", n2 - 1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse284 */
  @Test
  public void testParse284() {    // Elain: 284
    Elain elain = new Elain(); 
    elain.parse("   2  |  Karvatassu Mirzam   | Nelli"); 
    assertEquals("From: Elain line: 287", 2, elain.getTunnusNro()); 
    assertEquals("From: Elain line: 288", true, elain.toString().startsWith("2|Karvatassu Mirzam|Nelli|"));  // on enemmäkin kuin 3 kenttää, siksi loppu |
    elain.rekisteroi(); 
    int n = elain.getTunnusNro(); 
    elain.parse(""+(n+20));  // Otetaan merkkijonosta vain tunnusnumero
    elain.rekisteroi();  // ja tarkistetaan että seuraavalla kertaa tulee yhtä isompi
    assertEquals("From: Elain line: 294", n+20+1, elain.getTunnusNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAseta358 */
  @Test
  public void testAseta358() {    // Elain: 358
    Elain[] t = new Elain[5]; 
    Elain e = new Elain(); 
    String s = "Karhukolo"; 
    assertEquals("From: Elain line: 362", null, e.aseta(1,"Karhukolo Puh", t, s)); 
    assertEquals("From: Elain line: 363", "Nimen täytyy sisältää kasvattajan nimi ja eläimen nimi", e.aseta(1,"Nalle Puh", t, s)); 
    assertEquals("From: Elain line: 364", "Sirunumeron on oltava numeerinen", e.aseta(3,"nalle", t, s)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString426 */
  @Test
  public void testToString426() {    // Elain: 426
    Elain elain = new Elain(); 
    elain.parse("   2  |  Karvatassu Mirzam   | Nelli"); 
    assertEquals("From: Elain line: 429", true, elain.toString().startsWith("2|Karvatassu Mirzam|Nelli|"));  // on enemmäkin kuin 3 kenttää, siksi loppu |
  } // Generated by ComTest END
}