package pentu.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import pentu.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.23 21:51:57 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class OmistajaTest {



  // Generated by ComTest BEGIN
  /** testKaannaNimi214 */
  @Test
  public void testKaannaNimi214() {    // Omistaja: 214
    Omistaja o = new Omistaja(); 
    String s = "Aku Ankka"; 
    String s2 = o.kaannaNimi(s); 
    assertEquals("From: Omistaja line: 218", "Ankka Aku", s2); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi235 */
  @Test
  public void testRekisteroi235() {    // Omistaja: 235
    Omistaja a = new Omistaja(); 
    assertEquals("From: Omistaja line: 237", 0, a.getTunnusNro()); 
    a.rekisteroi(); 
    Omistaja b = new Omistaja(); 
    b.rekisteroi(); 
    int n1 = a.getTunnusNro(); 
    int n2 = b.getTunnusNro(); 
    assertEquals("From: Omistaja line: 243", n2 - 1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString302 */
  @Test
  public void testToString302() {    // Omistaja: 302
    Omistaja omistaja = new Omistaja(); 
    omistaja.parse("   3  |  Ari Katajavuori   | Kuusitie 12"); 
    assertEquals("From: Omistaja line: 305", true, omistaja.toString().startsWith("3|Ari Katajavuori|Kuusitie 12|"));  // on enemmäkin kuin 3 kenttää, siksi loppu |
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse336 */
  @Test
  public void testParse336() {    // Omistaja: 336
    Omistaja omistaja = new Omistaja(); 
    omistaja.parse("   1   |  Ari Katajavuori  |   Kuusitie 12  "); 
    assertEquals("From: Omistaja line: 339", 1, omistaja.getTunnusNro()); 
    assertEquals("From: Omistaja line: 340", true, omistaja.toString().startsWith("1|Ari Katajavuori|Kuusitie 12|")); 
    omistaja.rekisteroi(); 
    int n = omistaja.getTunnusNro(); 
    omistaja.parse(""+(n+20)); 
    omistaja.rekisteroi(); 
    assertEquals("From: Omistaja line: 346", n+20+1, omistaja.getTunnusNro()); 
  } // Generated by ComTest END
}