package pentu.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;

import java.util.ArrayList;

import org.junit.*;
import pentu.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.24 12:38:58 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class OmistajatTest {



  // Generated by ComTest BEGIN
  /** testLisaa49 */
  @Test
  public void testLisaa49() {    // Omistajat: 49
    Omistajat o = new Omistajat(); 
    Omistaja o2 = new Omistaja(); 
    Omistaja o3 = new Omistaja(); 
    Omistaja o4 = new Omistaja(); 
    o.lisaa(o2); o.lisaa(o3); o.lisaa(o4); 
    assertEquals("From: Omistajat line: 55", 3, o.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetOmistajat91 */
  @Test
  public void testGetOmistajat91() {    // Omistajat: 91
    Omistajat o = new Omistajat(); 
    Omistaja o1 = new Omistaja(); 
    Omistaja o2 = new Omistaja(); o2.parse("1|Ari Katajavuori|Kuusitie 12|10740 Helsinki|0405632942|ari.kvuori@gmail.com|"); 
    Omistaja o3 = new Omistaja(); o3.parse("2|Aino Alakiuttu|Pulukatu 24 B 5|40555 Pihtipudas|0503329471|aino4ever@hotmail.com|"); 
    Omistaja o4 = new Omistaja(); o4.parse("3|Pilvi Mannio|Linnantie 74|70860 Oulu|041542177|mannio.p@gmail.com|"); 
    o.lisaa(o1); o.lisaa(o2); o.lisaa(o3); o.lisaa(o4); 
    ArrayList<Omistaja> omistajat = o.getOmistajat(); 
    assertEquals("From: Omistajat line: 99", 4, omistajat.size()); 
    assertEquals("From: Omistajat line: 100", 2, omistajat.get(2).getTunnusNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPoista189 */
  @Test
  public void testPoista189() {    // Omistajat: 189
    Omistajat o = new Omistajat(); 
    Omistaja o1 = new Omistaja(); 
    Omistaja o2 = new Omistaja(); o2.parse("1|Ari Katajavuori|Kuusitie 12|10740 Helsinki|0405632942|ari.kvuori@gmail.com|"); 
    Omistaja o3 = new Omistaja(); o3.parse("2|Aino Alakiuttu|Pulukatu 24 B 5|40555 Pihtipudas|0503329471|aino4ever@hotmail.com|"); 
    Omistaja o4 = new Omistaja(); o4.parse("3|Pilvi Mannio|Linnantie 74|70860 Oulu|041542177|mannio.p@gmail.com|"); 
    o.lisaa(o1); o.lisaa(o2); o.lisaa(o3); o.lisaa(o4); 
    assertEquals("From: Omistajat line: 196", 4, o.getLkm()); 
    o.poista(o2); 
    assertEquals("From: Omistajat line: 198", 3, o.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLoytyyko217 */
  @Test
  public void testLoytyyko217() {    // Omistajat: 217
    Omistajat o = new Omistajat(); 
    Omistaja o1 = new Omistaja(); 
    Omistaja o2 = new Omistaja(); o2.parse("1|Ari Katajavuori|Kuusitie 12|10740 Helsinki|0405632942|ari.kvuori@gmail.com|"); 
    Omistaja o3 = new Omistaja(); o3.parse("2|Aino Alakiuttu|Pulukatu 24 B 5|40555 Pihtipudas|0503329471|aino4ever@hotmail.com|"); 
    Omistaja o4 = new Omistaja(); o4.parse("3|Pilvi Mannio|Linnantie 74|70860 Oulu|041542177|mannio.p@gmail.com|"); 
    o.lisaa(o1); o.lisaa(o2); o.lisaa(o3); o.lisaa(o4); 
    assertEquals("From: Omistajat line: 224", true, o.loytyyko(2)); 
    assertEquals("From: Omistajat line: 225", false, o.loytyyko(5)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testEtsi260 */
  @Test
  public void testEtsi260() {    // Omistajat: 260
    Omistajat o = new Omistajat(); 
    Omistaja o1 = new Omistaja(); 
    Omistaja o2 = new Omistaja(); o2.parse("1|Ari Katajavuori|Kuusitie 12|10740 Helsinki|0405632942|ari.kvuori@gmail.com|"); 
    Omistaja o3 = new Omistaja(); o3.parse("2|Aino Alakiuttu|Pulukatu 24 B 5|40555 Pihtipudas|0503329471|aino4ever@hotmail.com|"); 
    Omistaja o4 = new Omistaja(); o4.parse("3|Pilvi Mannio|Linnantie 74|70860 Oulu|041542177|mannio.p@gmail.com|"); 
    o.lisaa(o1); o.lisaa(o2); o.lisaa(o3); o.lisaa(o4); 
    ArrayList<Omistaja> lista = o.etsi("*v*", 1); 
    assertEquals("From: Omistajat line: 268", 2, lista.size()); 
    assertEquals("From: Omistajat line: 269", true, lista.get(0) == o2); 
    assertEquals("From: Omistajat line: 270", true, lista.get(1) == o4); 
    lista = o.etsi(null, -1); 
    assertEquals("From: Omistajat line: 273", 3, lista.size()); 
  } // Generated by ComTest END
}