package pentu.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import pentu.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.24 01:17:47 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PentuTest {



  // Generated by ComTest BEGIN
  /** testLisaa32 */
  @Test
  public void testLisaa32() {    // Pentu: 32
    Pentu pentu = new Pentu(); 
    Elain mirz1 = new Elain(), mirz2 = new Elain(); 
    assertEquals("From: Pentu line: 35", 0, pentu.getElaimia()); 
    pentu.lisaa(mirz1); assertEquals("From: Pentu line: 36", 1, pentu.getElaimia()); 
    pentu.lisaa(mirz2); assertEquals("From: Pentu line: 37", 2, pentu.getElaimia()); 
    pentu.lisaa(mirz1); assertEquals("From: Pentu line: 38", 3, pentu.getElaimia()); 
    assertEquals("From: Pentu line: 39", mirz1, pentu.annaElain(0)); 
    assertEquals("From: Pentu line: 40", mirz2, pentu.annaElain(1)); 
    assertEquals("From: Pentu line: 41", mirz1, pentu.annaElain(2)); 
    assertEquals("From: Pentu line: 42", false, pentu.annaElain(1) == mirz1); 
    assertEquals("From: Pentu line: 43", true, pentu.annaElain(1) == mirz2); 
    try {
    assertEquals("From: Pentu line: 44", mirz1, pentu.annaElain(3)); 
    fail("Pentu: 44 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    pentu.lisaa(mirz1); assertEquals("From: Pentu line: 45", 4, pentu.getElaimia()); 
    pentu.lisaa(mirz2); assertEquals("From: Pentu line: 46", 5, pentu.getElaimia()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLisaa58 */
  @Test
  public void testLisaa58() {    // Pentu: 58
    Pentu pentu = new Pentu(); 
    Omistaja a = new Omistaja(), b = new Omistaja(); 
    assertEquals("From: Pentu line: 61", 0, pentu.getOmistajia()); 
    pentu.lisaa(a); assertEquals("From: Pentu line: 62", 1, pentu.getOmistajia()); 
    pentu.lisaa(b); assertEquals("From: Pentu line: 63", 2, pentu.getOmistajia()); 
    pentu.lisaa(a); assertEquals("From: Pentu line: 64", 3, pentu.getOmistajia()); 
    assertEquals("From: Pentu line: 65", a, pentu.annaOmistaja(0)); 
    assertEquals("From: Pentu line: 66", b, pentu.annaOmistaja(1)); 
    assertEquals("From: Pentu line: 67", a, pentu.annaOmistaja(2)); 
    assertEquals("From: Pentu line: 68", false, pentu.annaOmistaja(1) == a); 
    assertEquals("From: Pentu line: 69", true, pentu.annaOmistaja(1) == b); 
    try {
    assertEquals("From: Pentu line: 70", a, pentu.annaOmistaja(3)); 
    fail("Pentu: 70 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    pentu.lisaa(a); assertEquals("From: Pentu line: 71", 4, pentu.getOmistajia()); 
    pentu.lisaa(b); assertEquals("From: Pentu line: 72", 5, pentu.getOmistajia()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaElain118 */
  @Test
  public void testAnnaElain118() {    // Pentu: 118
    Pentu pentu = new Pentu(); 
    Elain mirz1 = new Elain(), mirz2 = new Elain(); 
    pentu.lisaa(mirz1); pentu.lisaa(mirz2); pentu.lisaa(mirz1); 
    assertEquals("From: Pentu line: 122", mirz1, pentu.annaElain(0)); 
    assertEquals("From: Pentu line: 123", mirz2, pentu.annaElain(1)); 
    assertEquals("From: Pentu line: 124", mirz1, pentu.annaElain(2)); 
    assertEquals("From: Pentu line: 125", false, pentu.annaElain(1) == mirz1); 
    assertEquals("From: Pentu line: 126", true, pentu.annaElain(1) == mirz2); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaOmistaja140 */
  @Test
  public void testAnnaOmistaja140() {    // Pentu: 140
    Pentu pentu = new Pentu(); 
    Omistaja a = new Omistaja(), b = new Omistaja(); 
    assertEquals("From: Pentu line: 143", 0, pentu.getOmistajia()); 
    pentu.lisaa(a); 
    pentu.lisaa(b); 
    pentu.lisaa(a); 
    assertEquals("From: Pentu line: 147", a, pentu.annaOmistaja(0)); 
    assertEquals("From: Pentu line: 148", b, pentu.annaOmistaja(1)); 
    assertEquals("From: Pentu line: 149", a, pentu.annaOmistaja(2)); 
    assertEquals("From: Pentu line: 150", false, pentu.annaOmistaja(1) == a); 
    assertEquals("From: Pentu line: 151", true, pentu.annaOmistaja(1) == b); 
  } // Generated by ComTest END
}